# Generated by Django 4.0.6 on 2022-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='note',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
