# Generated by Django 4.0.6 on 2022-08-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_itemcard_is_transforming'),
        ('accounting_manager', '0002_alter_expenses_date_alter_expenses_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemcard')),
            ],
        ),
    ]
