# Generated by Django 4.0.6 on 2022-08-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_itemcard_is_transforming'),
        ('accounting_manager', '0004_remove_pricingrequest_item_card_pricingrequest_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('seller', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemtype')),
            ],
        ),
    ]
