# Generated by Django 4.0.6 on 2022-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_manager', '0005_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(),
        ),
    ]
