# Generated by Django 4.0.6 on 2022-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_manager', '0006_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
