# Generated by Django 4.1.1 on 2022-09-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0004_stock_is_main_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_main_storage',
        ),
    ]
