# Generated by Django 4.1.1 on 2022-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0005_remove_stock_is_main_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='is_retail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
