# Generated by Django 4.0.6 on 2022-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='receiving_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('In-Progress', 'In-Progress'), ('On-Time', 'On-Time'), ('Late-Submission', 'Late-Submission'), ('Deadlined', 'Deadlined')], default='In-Progress', max_length=20, null=True),
        ),
    ]
