# Generated by Django 4.0.6 on 2022-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_alter_task_receiving_date_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='receiving_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
