# Generated by Django 4.1.1 on 2022-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_alter_task_receiving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('In-Progress', 'In-Progress'), ('On-Time', 'On-Time'), ('Late-Submission', 'Late-Submission'), ('Overdue', 'Overdue')], default='In-Progress', max_length=20, null=True),
        ),
    ]
