# Generated by Django 4.1.1 on 2022-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='-', max_length=500, null=True),
        ),
    ]
