# Generated by Django 4.0.6 on 2022-08-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0028_itemcard_is_priced'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('received_from', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemtype')),
            ],
        ),
    ]
