# Generated by Django 4.0.6 on 2022-08-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Ended', 'Ended')], default=('Running', 'Running'), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='facebook',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='instagram',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shopee',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
