# Generated by Django 4.0.6 on 2022-08-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_manager', '0002_questionnaire_status_alter_customer_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Closed', 'Closed')], default=('Pending', 'Pending'), max_length=10, null=True),
        ),
    ]
