# Generated by Django 4.0.6 on 2022-08-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_manager', '0003_alter_questionnaire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='numbers_of_questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Closed', 'Closed')], default='Pending', max_length=10, null=True),
        ),
    ]
