# Generated by Django 4.0.6 on 2022-07-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contacting_email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('photo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.account')),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person')),
            ],
        ),
    ]
