# Generated by Django 4.0.6 on 2022-07-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_id_alter_employee_id_alter_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Human Resources', 'Human Resources'), ('Warehouse Admin', 'Warehouse Admin'), ('Accounting Manager', 'Accounting Manager'), ('Social Media MAnager', 'Social Media MAnager'), ('Designer', 'Designer'), ('Distributor', 'Distributor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(choices=[('YEM', 'YEMEN'), ('ID', 'INDONESIA')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
