# Generated by Django 4.0.6 on 2022-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_stock_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Human Resources', 'Human Resources'), ('Warehouse Admin', 'Warehouse Admin'), ('Accounting Manager', 'Accounting Manager'), ('Social Media MAnager', 'Social Media Manager'), ('Designer', 'Designer'), ('Distributor', 'Distributor')], max_length=20),
        ),
    ]
