# Generated by Django 4.0.6 on 2022-07-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('In-Progress', 'In-Progress'), ('On-Time', 'On-Time'), ('Late-Submission', 'Late-Submission'), ('Declined', 'Declined')], max_length=20, null=True)),
                ('receiving_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('week_end_date', models.DateField(blank=True, null=True)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_time', models.FloatField()),
                ('rate', models.FloatField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
