# Generated by Django 4.0.6 on 2022-08-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_on_time_taskrate_on_time_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrate',
            name='employee',
            field=models.ManyToManyField(to='main.employee'),
        ),
    ]
