# Generated by Django 4.0.6 on 2022-08-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_weeklyrate_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('week_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklyrate',
            name='week_end_date',
        ),
        migrations.RemoveField(
            model_name='weeklyrate',
            name='week_start_date',
        ),
        migrations.AddField(
            model_name='weeklyrate',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.week'),
        ),
    ]
