# Generated by Django 4.0.6 on 2022-08-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_week_remove_weeklyrate_week_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrate',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week'),
        ),
    ]
