# Generated by Django 4.0.6 on 2022-08-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_batch_itemtype_price_retailcard_itemcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='receiving_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retailcard',
            name='conversion_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
