# Generated by Django 4.0.6 on 2022-08-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_batch_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemcard')),
            ],
        ),
    ]
