# Generated by Django 4.0.6 on 2022-08-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_goodsmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='is_retail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RetailItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.price')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemtype')),
            ],
        ),
    ]
