# Generated by Django 4.0.6 on 2022-08-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_itemtype_is_retail_retailitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailcard',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='retailcard',
            name='stock',
        ),
    ]
