# Generated by Django 4.0.6 on 2022-08-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_retailcard_batch_remove_retailcard_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='is_transforming',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
