# Generated by Django 4.0.6 on 2022-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_itemcard_is_transforming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcard',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Frozen', 'Frozen')], default='Good', max_length=10),
        ),
    ]
