# Generated by Django 4.0.6 on 2022-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_goodsmovement_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='is_priced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
