# Generated by Django 4.0.6 on 2022-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_itemcard_is_priced'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_Rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
