# Generated by Django 4.0.6 on 2022-08-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_week_is_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='is_Rated',
            new_name='is_tated',
        ),
    ]
