# Generated by Django 4.0.6 on 2022-08-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_is_rated_week_is_tated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='is_tated',
            new_name='is_rated',
        ),
    ]
