# Generated by Django 4.0.6 on 2022-08-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_is_tated_week_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrate',
            name='employee',
        ),
        migrations.AddField(
            model_name='weeklyrate',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee'),
        ),
    ]
