# Generated by Django 4.0.6 on 2022-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_weeklyrate_employee_weeklyrate_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('In-Progress', 'In-Progress'), ('On-Time', 'On-Time'), ('Late-Submission', 'Late-Submission'), ('Deadlined', 'Deadlined')], max_length=20, null=True),
        ),
    ]
